# Generated by Django 5.2.7 on 2025-10-14 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_avatar_user_bio_favorite_image_favorited_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='相册名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='相册简介')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '相册',
                'verbose_name_plural': '相册',
                'db_table': 'albums',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlbumImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.album')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.image')),
            ],
            options={
                'verbose_name': '相册图片',
                'verbose_name_plural': '相册图片',
                'db_table': 'album_images',
                'ordering': ['-added_at'],
                'unique_together': {('album', 'image')},
            },
        ),
        migrations.AddField(
            model_name='album',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='albums', through='api.AlbumImage', to='api.image'),
        ),
    ]
